### ISSUE TITLE
fix: Cannot find module '@nuxtjs/composition-api/entrypoint'  

### ISSUE THREAD

**Issue by yoshixj** [nuxt-community/composition-api#412]
**🐛 The bug**

When I setup composition api followed the steps,  it didn't work correctly.
https://composition-api.nuxtjs.org/getting-started/setup

The error is as follows
```sh
$ yarn dev
yarn run v1.22.4
$ nuxt-ts

 WARN  You're using Nuxt 2.15.3, which includes built-in TypeScript runtime support                                                      13:19:55


 WARN  You can safely use nuxt instead of nuxt-ts and remove @nuxt/typescript-runtime package                                            13:19:55


 FATAL  Cannot find module '@nuxtjs/composition-api/entrypoint'                                                                          13:19:56
Require stack:
- /Users/yoshikimasubuchi/.ghq/github.com/NiCOLA-inc/doughnut/node_modules/@nuxtjs/composition-api/lib/index.js
- /Users/yoshikimasubuchi/.ghq/github.com/NiCOLA-inc/doughnut/node_modules/@nuxt/core/dist/core.js

  Require stack:
  - node_modules/@nuxtjs/composition-api/lib/index.js
  - node_modules/@nuxt/core/dist/core.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
  at Function.a [as resolve] (node_modules/jiti/dist/v8cache.js:2:2385)
  at ModuleContainer.addResolvedTemplate (node_modules/@nuxtjs/composition-api/lib/index.js:45:23)
  at ModuleContainer.compositionApiModule2 (node_modules/@nuxtjs/composition-api/lib/index.js:170:41)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:34)
  at node_modules/@nuxt/utils/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)


   ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                     │
   │   ✖ Nuxt Fatal Error                                                                                                │
   │                                                                                                                     │
   │   Error: Cannot find module '@nuxtjs/composition-api/entrypoint'                                                    │
   │   Require stack:                                                                                                    │
   │   - /Users/yoshikimasubuchi/.ghq/github.com/NiCOLA-inc/doughnut/node_modules/@nuxtjs/composition-api/lib/index.js   │
   │   - /Users/yoshikimasubuchi/.ghq/github.com/NiCOLA-inc/doughnut/node_modules/@nuxt/core/dist/core.js                │
   │                                                                                                                     │
   ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**🛠️ To reproduce**
1. create-nuxt-app
2. install `@nuxtjs/composition-api` module
3. add `@nuxtjs/composition-api` to nuxt.config.js

```
$ create-nuxt-app doughnut

create-nuxt-app v3.5.2
✨  Generating Nuxt.js project in doughnut
? Project name: doughnut
? Programming language: TypeScript
? Package manager: Yarn
? UI framework: Tailwind CSS
? Nuxt.js modules: Axios - Promise based HTTP client, Progressive Web App (PWA)
? Linting tools: ESLint, Prettier, Lint staged files, StyleLint
? Testing framework: Jest
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)
? Development tools: jsconfig.json (Recommended for VS Code if you're not using typescript)
? Continuous integration: None
? Version control system: Git
yarn run v1.22.4
$ eslint --ext ".js,.vue" --ignore-path .gitignore . --fix
✨  Done in 2.70s.
yarn run v1.22.4
$ stylelint "**/*.{vue,css}" --ignore-path .gitignore --fix
✨  Done in 0.87s.

🎉  Successfully created project doughnut

  To get started:

        cd doughnut
        yarn dev

  To build & start for production:

        cd doughnut
        yarn build
        yarn start

  To test:

        cd doughnut
        yarn test


  For TypeScript users.

  See : https://typescript.nuxtjs.org/cookbook/components/


$ yarn add @nuxtjs/composition-api
yarn add v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@nuxtjs/composition-api > @vue/composition-api@1.0.0-rc.5" has unmet peer dependency "vue@>= 2.5 < 3".
warning " > @nuxtjs/composition-api@0.22.3" has unmet peer dependency "@nuxt/vue-app@^2.15".
warning " > @nuxtjs/composition-api@0.22.3" has unmet peer dependency "fs-extra@^8.1.0".
warning " > @nuxtjs/composition-api@0.22.3" has unmet peer dependency "nuxt@^2.15".
warning " > @nuxtjs/composition-api@0.22.3" has unmet peer dependency "vue@^2".
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
success Saved 9 new dependencies.
info Direct dependencies
└─ @nuxtjs/composition-api@0.22.3
info All dependencies
├─ @nuxtjs/composition-api@0.22.3
├─ @vue/composition-api@1.0.0-rc.5
├─ defu@3.2.2
├─ estree-walker@2.0.2
├─ magic-string@0.25.7
├─ sourcemap-codec@1.4.8
├─ tslib@2.1.0
├─ ufo@0.6.10
└─ upath@2.0.1
✨  Done in 0.64s.
```

`nuxt.config.js`
```js
~ 
buildModules: [
    // https://go.nuxtjs.dev/typescript
    '@nuxt/typescript-build',
    // https://go.nuxtjs.dev/stylelint
    '@nuxtjs/stylelint-module',
    // https://go.nuxtjs.dev/tailwindcss
    '@nuxtjs/tailwindcss',
    '@nuxtjs/composition-api',
  ],
~
```

**🌈 Expected behaviour**
What did you expect to happen? Is there a section in the docs about this?

**ℹ️ Additional context**

**Comment by yoshixj** [comment]
This Bug may be occured by this update.

```git

 "@nuxtjs/composition-api@^0.22.0":
-  version "0.22.0"
-  resolved "https://registry.yarnpkg.com/@nuxtjs/composition-api/-/composition-api-0.22.0.tgz#4ce65673dd08ef3d864ff35556e311224f16ffa2"
-  integrity sha512-FnrnYkCog3/N5T13vFcKKn0wu0Ifsh64OgS4e0PFESe+ON0AheXBYfPhpR7jxAAGBaFmz/8OMD4+LKYaQhxT9w==
+  version "0.22.3"
+  resolved "https://registry.yarnpkg.com/@nuxtjs/composition-api/-/composition-api-0.22.3.tgz#fd715670bb0ae1b536b9b2c1aba359db16718063"
+  integrity sha512-yD3jiGMotMpUPsHh3bEEd+plJu63/lwJfd5rHHYpBjlkoopEacfIxYgFnGp479FoeIqXZlaAWGxEw4BG2E4b0A==
   dependencies:
-    "@vue/composition-api" "1.0.0-rc.3"
+    "@vue/composition-api" "1.0.0-rc.5"
     defu "^3.2.2"
     estree-walker "^2.0.2"
     magic-string "^0.25.7"
-    ufo "^0.6.9"
+    ufo "^0.6.10"
     upath "^2.0.1"

```

**Comment by danielroe** [comment]
See #410. Make sure you're using a current version of Node.

**Comment by yoshixj** [comment]
Upadating my local node version to v15.90 solves this problem!!

Thank you for comment!
