### ISSUE TITLE
help: issue with fetching

### ISSUE THREAD

**Issue by congyaqwq** [nuxt-community/composition-api#422]
**📚 What are you trying to do? Please describe.**
I run my vue 3.0 project successfully, but the page source didn't show my data, and send me a error message; 
Code  
```javascript
setup() {
    const route = useRoute();
    const data = ref({});
    const { id = "" } = route.value.params;
    const fetchData = async () => {
      let detail = await Api.detail(id);
      detail.content = marked(detail.content);
      data.value = detail;
    };

    const { fetch, fetchstate } = useFetch(async () => {
      await fetchData();
    });
    fetch();
    fetchstate;

    return {
      data,
    };
  },
```
Error  
```
 ERROR  Error in fetch(): Cannot read property 'data' of undefined                                                                                                            18:17:54

  at module.exports../utils/request.js.baseURL (server.js:5693:19)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```
(Sorry,My English is poor.)

**Comment by congyaqwq** [comment]
I mean, data taken from the back end is not shown in the source code. Also I want to know how to solve the error. Thanks!

**Comment by congyaqwq** [comment]
For SEO, I change my Vue3 project with nuxt, and I found it's works well, so I didn't notice it's based on Vue2. I will try use fetch in onMounted.

**Comment by congyaqwq** [comment]
I found the question, It cause by axiox, It maybe used by other library, so I need to create a new instance;
`const instance = axios.create()`
My project run successfully, I will read the document carefully next time ! Thank you !
