### ISSUE TITLE
fix: v0.22.4 not working with nuxt-vite

### ISSUE THREAD

**Issue by kumasuke** [nuxt-community/composition-api#443]
**🐛 The bug**
It not worked since `v0.22.2`.
but `v0.22.1` is worked.
It worked without "nuxt-vite".

error occurs:
```
 ERROR  'globalPlugin' is not exported by .nuxt/composition-api/entrypoint.js, imported by defaultexport:/sandbox/.nuxt/composition-api/plugin.js


 ERROR  file: defaultexport:/sandbox/.nuxt/composition-api/plugin.js:1:8


 ERROR  1: import {globalPlugin} from "@nuxtjs/composition-api";      03:49:31
           ^
2: export default globalPlugin;


 ERROR  'globalPlugin' is not exported by .nuxt/composition-api/entrypoint.js, imported by defaultexport:/sandbox/.nuxt/composition-api/plugin.js

  at error (node_modules/rollup/dist/shared/rollup.js:5305:30)
  at Module.error (node_modules/rollup/dist/shared/rollup.js:9750:16)
  at Module.traceVariable (node_modules/rollup/dist/shared/rollup.js:10138:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/shared/rollup.js:8899:39)
  at Identifier.bind (node_modules/rollup/dist/shared/rollup.js:4035:40)
  at ExportDefaultDeclaration.bind (node_modules/rollup/dist/shared/rollup.js:2734:23)
  at Program.bind (node_modules/rollup/dist/shared/rollup.js:2730:31)
  at Module.bindReferences (node_modules/rollup/dist/shared/rollup.js:9746:18)
  at Graph.sortModules (node_modules/rollup/dist/shared/rollup.js:19400:20)
  at Graph.build (node_modules/rollup/dist/shared/rollup.js:19281:14)
  at async rollupInternal (node_modules/rollup/dist/shared/rollup.js:20207:9)
  at async doBuild (node_modules/vite/dist/node/chunks/dep-66eb515d.js:44228:24)
  at async Object.build (node_modules/vite/dist/node/chunks/dep-66eb515d.js:44174:16)
  at async node_modules/nuxt-vite/dist/nuxt-vite.js-vite.js:191:5
```

This is an error that occurred in "Codesandbox", but it also occurs in the local.
Similar to #286.

**🛠️ To reproduce**
1. yarn create nuxt-app
2. yarn add `@nuxtjs/composition-api` `nuxt-vite`
3. add buildModules "nuxt-vite", "@nuxtjs/composition-api" in nuxt.config
4. run dev
5. error occurred

**ℹ️ Additional context**
- @nuxtjs/composition-api@0.22.4
- nuxt@2.15.4
- nuxt-vite@0.0.36

**Comment by reslear** [comment]
same

**Comment by kumasuke** [comment]
@danielroe 
Thanks for the update.
But I got another error.
Without nuxt-vite, it works.

browser error:
```
Uncaught SyntaxError: The requested module '/@fs/Users/workspace/***/node_modules/.cache/vite/client/@nuxtjs_composition-api.js?v=f6d2725f' does not provide an export named 'default'
```

server error:
```
ERROR  Cannot set property 'NrOjtNJNIsZS0mYzSXbARg==' of undefined                                                                                          23:45:46
  at setData (node_modules/.pnpm/@nuxtjs+composition-api@0.23.0_nuxt@2.15.4/node_modules/@nuxtjs/composition-api/dist/index.js:54:69)
  at RefImpl.set [as value] (node_modules/.pnpm/@nuxtjs+composition-api@0.23.0_nuxt@2.15.4/node_modules/@nuxtjs/composition-api/dist/index.js:101:7)
  at node_modules/.pnpm/@nuxtjs+composition-api@0.23.0_nuxt@2.15.4/node_modules/@nuxtjs/composition-api/dist/index.js:152:34
```
